services:
  catalog-db:
    image: postgres:17-alpine
    container_name: catalog-db
    ports:
      - "5432:5432"
    networks:
      - ecomm-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: catalog

  # Нода 1 (Master + TServer)
  yb-master:
    image: yugabytedb/yugabyte:2024.2.3.1-b3
    container_name: yb-master
    command: ["bin/yb-master", "--fs_data_dirs=/data/master", "--master_addresses=yb-master:7100"]
    ports:
      - "7000:7000"
      - "7100:7100"
    networks:
      - ecomm-net
    volumes:
      - master_data:/data/master

  yb-tserver1:
    image: yugabytedb/yugabyte:2024.2.3.1-b3
    container_name: yb-tserver1
    depends_on: [yb-master]
    command: ["bin/yb-tserver", "--fs_data_dirs=/data/tserver1", "--tserver_master_addrs=yb-master:7100", "--start_pgsql_proxy"]
    ports:
      - "9001:9000"
      - "5433:5433"
    networks:
      - ecomm-net
    volumes:
      - tserver1_data:/data/tserver1

  yb-tserver2:
    image: yugabytedb/yugabyte:2024.2.3.1-b3
    container_name: yb-tserver2
    depends_on: [yb-master]
    command: ["bin/yb-tserver", "--fs_data_dirs=/data/tserver2", "--tserver_master_addrs=yb-master:7100", "--start_pgsql_proxy"]
    ports:
      - "9002:9000"
      - "5434:5433"
    networks:
      - ecomm-net
    volumes:
      - tserver2_data:/data/tserver2

  yb-tserver3:
    image: yugabytedb/yugabyte:2024.2.3.1-b3
    container_name: yb-tserver3
    depends_on: [yb-master]
    command: ["bin/yb-tserver", "--fs_data_dirs=/data/tserver3", "--tserver_master_addrs=yb-master:7100", "--start_pgsql_proxy"]
    ports:
      - "9003:9000"
      - "5435:5433"
    networks:
      - ecomm-net
    volumes:
      - tserver3_data:/data/tserver3

  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - ecomm-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - ecomm-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo

volumes:
  mongo_data:
  tserver3_data:
  tserver2_data:
  tserver1_data:
  master_data:


networks:
  ecomm-net:
    driver: bridge