ca:
  cn: "Glob CA"
  key_size: 4096
  validity_days: 365

servers:
- cn: "localhost"
  sans:
  - "IP:0.0.0.0"
  - "IP:localhost"
  - "DNS:*.example.com"
  - "IP:127.0.0.1"
  key_size: 4096
  validity_days: 90

clients:
- cn: "mobile-client"
  validity_days: 180
